#ifndef tools_CommandLineParser_h
#define tools_CommandLineParser_h

#include <vector>
#include <map>
#include <string>
#include <system_error>

namespace tools
{
	/** @brief Simple class to parse the command line arguments.
	 *
	 * @author Mark Grimes
	 * @date 12/Aug/2013
	 */
	class CommandLineParser
	{
	public:
		/** @brief Error codes that can be generated by the class. */
		enum class error { ok=0, parse_error, unknown_option, unexepected_option_value, missing_option_value, option_as_value };
	public:
		enum ArgumentType { NoArgument, RequiredArgument, OptionalArgument };
		void addOption( const std::string& name, ArgumentType argumentType );
		/** @brief Parses the command line, for later querying by the query methods.
		 *
		 * @throw std::runtime_error     If there are any problems, e.g. invalid option specifications.
		 */
		void parse( const int argc, char const* const* argv );
		/** @brief Non throwing version of parse, where errors are reported in the std::error_code supplied. */
		void parse( const int argc, char const* const* argv, std::error_code& error );
		bool optionHasBeenSet( const std::string& optionName ) const;
		const std::vector<std::string>& optionArguments( const std::string& optionName ) const;
		const std::vector<std::string>& nonOptionArguments() const;
		const std::string& executableName() const;
	protected:
		std::string executableName_; ///< @brief The name of the executable called. Useful for printing usage information.
		std::map<std::string,std::vector<std::string> > parsedOptions_;
		std::vector<std::string> nonOptionArguments_;
		std::vector<std::pair<std::string,ArgumentType> > allowedOptions_;
		std::vector<std::string> emptyVector_; ///< @brief Sometimes I need to return empty vectors, but I need to return a reference. This stays in scope.
		std::vector<std::pair<error,std::string> > parseErrors_; ///< @brief A record of the parsing errors and the option that caused the error
	};
} // end of the tools namespace

//
// Functions/structs required to get automatic conversion of CommandLineParser::error
// to std::error_code. For more information on this see
// http://blog.think-async.com/2010/04/system-error-support-in-c0x-part-4.html
//
namespace tools
{
	std::error_code make_error_code( tools::CommandLineParser::error e );
	std::error_condition make_error_condition( tools::CommandLineParser::error e );
}
namespace std
{
	template<> struct is_error_code_enum<tools::CommandLineParser::error> : public true_type {};
}

#endif
